name: Build APK
on: 
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python_version: '3.10'

      - name: Install System Dependencies
        run: |
          sudo apt update
          sudo apt install -y git zip unzip autoconf autotools-dev libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev build-essential python3-dev
          pip install --upgrade pip
          pip install --upgrade Cython==0.29.33 buildozer

      - name: Build Android APK
        run: |
          # Perintah 'yes' digunakan untuk menjawab 'y' secara automatik pada lesen Android
          yes | buildozer -v android debug
        
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: PalmGrade-APK-Result
          path: bin/*.apk
